class Countries {
  static List<Country> countries = [
    Country(
        name: 'Afghanistan',
        a2: 'AF',
        a3: 'AFG',
        num: '4',
        itu: 'AFG',
        gec: 'AF',
        ioc: 'AFG',
        fifa: 'AFG',
        ds: 'AFG',
        wmo: 'AF',
        gaul: '1',
        marc: 'af',
        dial: '93',
        independent: 'Yes'),
    Country(
      name: 'Aland',
      a2: 'AX',
      a3: 'ALA',
      num: '248',
      itu: '',
      gec: '',
      ioc: '',
      fifa: 'ALD',
      ds: 'FIN',
      wmo: '',
      gaul: '1242',
      marc: '',
      dial: '358',
      independent: 'Part of FI',
    ),
    Country(
      name: 'Albania',
      a2: 'AL',
      a3: 'ALB',
      num: '8',
      itu: 'ALB',
      gec: 'AL',
      ioc: 'ALB',
      fifa: 'ALB',
      ds: 'AL',
      wmo: 'AB',
      gaul: '3',
      marc: 'aa',
      dial: '355',
      independent: 'Yes',
    ),
    Country(
      name: 'Algeria',
      a2: 'DZ',
      a3: 'DZA',
      num: '12',
      itu: 'ALG',
      gec: 'AG',
      ioc: 'ALG',
      fifa: 'ALG',
      ds: 'DZ',
      wmo: 'AL',
      gaul: '4',
      marc: 'ae',
      dial: '213',
      independent: 'Yes',
    ),
    Country(
      name: 'American Samoa',
      a2: 'AS',
      a3: 'ASM',
      num: '16',
      itu: 'SMA',
      gec: 'AQ',
      ioc: 'ASA',
      fifa: 'ASA',
      ds: 'USA',
      gaul: '5',
      marc: 'as',
      dial: '1-684',
      independent: 'Territory of US',
    ),
    Country(
      name: 'Andorra',
      a2: 'AD',
      a3: 'AND',
      num: '20',
      itu: 'AND',
      gec: 'AN',
      ioc: 'AND',
      fifa: 'AND',
      ds: 'AND',
      gaul: '7',
      marc: 'an',
      dial: '376',
      independent: 'Yes',
    ),
    Country(
      name: 'Angola',
      a2: 'AO',
      a3: 'AGO',
      num: '24',
      itu: 'AGL',
      gec: 'AO',
      ioc: 'ANG',
      fifa: 'ANG',
      ds: 'AO',
      wmo: 'AN',
      gaul: '8',
      marc: 'ao',
      dial: '244',
      independent: 'Yes',
    ),
    Country(
      name: 'Anguilla',
      a2: 'AI',
      a3: 'AIA',
      num: '660',
      itu: 'AIA',
      gec: 'AV',
      ioc: 'AIA',
      fifa: 'AIA',
      gaul: '9',
      marc: 'am',
      dial: '1-264',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Antarctica',
      a2: 'AQ',
      a3: 'ATA',
      num: '10',
      gec: 'AY',
      fifa: 'ROS',
      wmo: 'AA',
      gaul: '10',
      marc: 'ay',
      dial: '672',
      independent: 'International',
    ),
    Country(
      name: 'Antigua and Barbuda',
      a2: 'AG',
      a3: 'ATG',
      num: '28',
      itu: 'ATG',
      gec: 'AC',
      ioc: 'ANT',
      fifa: 'ATG',
      wmo: 'AT',
      gaul: '11',
      marc: 'aq',
      dial: '1-268',
      independent: 'Yes',
    ),
    Country(
      name: 'Argentina',
      a2: 'AR',
      a3: 'ARG',
      num: '32',
      itu: 'ARG',
      gec: 'AR',
      ioc: 'ARG',
      fifa: 'ARG',
      ds: 'RA',
      wmo: 'AG',
      gaul: '12',
      marc: 'ag',
      dial: '54',
      independent: 'Yes',
    ),
    Country(
      name: 'Armenia',
      a2: 'AM',
      a3: 'ARM',
      num: '51',
      itu: 'ARM',
      gec: 'AM',
      ioc: 'ARM',
      fifa: 'ARM',
      ds: 'AM',
      wmo: 'AY',
      gaul: '13',
      marc: 'ai',
      dial: '374',
      independent: 'Yes',
    ),
    Country(
      name: 'Aruba',
      a2: 'AW',
      a3: 'ABW',
      num: '533',
      itu: 'ABW',
      gec: 'AA',
      ioc: 'ARU',
      fifa: 'ARU',
      ds: 'AW',
      wmo: 'NU',
      gaul: '14',
      marc: 'aw',
      dial: '297',
      independent: 'Part of NL',
    ),
    Country(
      name: 'Australia',
      a2: 'AU',
      a3: 'AUS',
      num: '36',
      itu: 'AUS',
      gec: 'AS',
      ioc: 'AUS',
      fifa: 'AUS',
      ds: 'AUS',
      wmo: 'AU',
      gaul: '17',
      marc: 'at',
      dial: '61',
      independent: 'Yes',
    ),
    Country(
      name: 'Austria',
      a2: 'AT',
      a3: 'AUT',
      num: '40',
      itu: 'AUT',
      gec: 'AU',
      ioc: 'AUT',
      fifa: 'AUT',
      ds: 'A',
      wmo: 'OS',
      gaul: '18',
      marc: 'au',
      dial: '43',
      independent: 'Yes',
    ),
    Country(
      name: 'Azerbaijan',
      a2: 'AZ',
      a3: 'AZE',
      num: '31',
      itu: 'AZE',
      gec: 'AJ',
      ioc: 'AZE',
      fifa: 'AZE',
      ds: 'AZ',
      wmo: 'AJ',
      gaul: '19',
      marc: 'aj',
      dial: '994',
      independent: 'Yes',
    ),
    Country(
      name: 'Bahamas',
      a2: 'BS',
      a3: 'BHS',
      num: '44',
      itu: 'BAH',
      gec: 'BF',
      ioc: 'BAH',
      fifa: 'BAH',
      ds: 'BS',
      wmo: 'BA',
      gaul: '20',
      marc: 'bf',
      dial: '1-242',
      independent: 'Yes',
    ),
    Country(
      name: 'Bahrain',
      a2: 'BH',
      a3: 'BHR',
      num: '48',
      itu: 'BHR',
      gec: 'BA',
      ioc: 'BRN',
      fifa: 'BHR',
      ds: 'BRN',
      wmo: 'BN',
      gaul: '21',
      marc: 'ba',
      dial: '973',
      independent: 'Yes',
    ),
    Country(
      name: 'Bangladesh',
      a2: 'BD',
      a3: 'BGD',
      num: '50',
      itu: 'BGD',
      gec: 'BG',
      ioc: 'BAN',
      fifa: 'BAN',
      ds: 'BD',
      wmo: 'BW',
      gaul: '23',
      marc: 'bg',
      dial: '880',
      independent: 'Yes',
    ),
    Country(
      name: 'Barbados',
      a2: 'BB',
      a3: 'BRB',
      num: '52',
      itu: 'BRB',
      gec: 'BB',
      ioc: 'BAR',
      fifa: 'BRB',
      ds: 'Bds',
      wmo: 'BR',
      gaul: '24',
      marc: 'bb',
      dial: '1-246',
      independent: 'Yes',
    ),
    Country(
      name: 'Belarus',
      a2: 'BY',
      a3: 'BLR',
      num: '112',
      itu: 'BLR',
      gec: 'BO',
      ioc: 'BLR',
      fifa: 'BLR',
      ds: 'BY',
      wmo: 'BY',
      gaul: '26',
      marc: 'bw',
      dial: '375',
      independent: 'Yes',
    ),
    Country(
      name: 'Belgium',
      a2: 'BE',
      a3: 'BEL',
      num: '56',
      itu: 'BEL',
      gec: 'BE',
      ioc: 'BEL',
      fifa: 'BEL',
      ds: 'B',
      wmo: 'BX',
      gaul: '27',
      marc: 'be',
      dial: '32',
      independent: 'Yes',
    ),
    Country(
      name: 'Belize',
      a2: 'BZ',
      a3: 'BLZ',
      num: '84',
      itu: 'BLZ',
      gec: 'BH',
      ioc: 'BIZ',
      fifa: 'BLZ',
      ds: 'BH',
      wmo: 'BH',
      gaul: '28',
      marc: 'bh',
      dial: '501',
      independent: 'Yes',
    ),
    Country(
      name: 'Benin',
      a2: 'BJ',
      a3: 'BEN',
      num: '204',
      itu: 'BEN',
      gec: 'BN',
      ioc: 'BEN',
      fifa: 'BEN',
      ds: 'DY',
      wmo: 'BJ',
      gaul: '29',
      marc: 'dm',
      dial: '229',
      independent: 'Yes',
    ),
    Country(
      name: 'Bermuda',
      a2: 'BM',
      a3: 'BMU',
      num: '60',
      itu: 'BER',
      gec: 'BD',
      ioc: 'BER',
      fifa: 'BER',
      ds: 'BM',
      wmo: 'BE',
      gaul: '30',
      marc: 'bm',
      dial: '1-441',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Bhutan',
      a2: 'BT',
      a3: 'BTN',
      num: '64',
      itu: 'BTN',
      gec: 'BT',
      ioc: 'BHU',
      fifa: 'BHU',
      ds: 'BT',
      gaul: '31',
      marc: 'bt',
      dial: '975',
      independent: 'Yes',
    ),
    Country(
      name: 'Bolivia',
      a2: 'BO',
      a3: 'BOL',
      num: '68',
      itu: 'BOL',
      gec: 'BL',
      ioc: 'BOL',
      fifa: 'BOL',
      ds: 'BOL',
      wmo: 'BO',
      gaul: '33',
      marc: 'bo',
      dial: '591',
      independent: 'Yes',
    ),
    Country(
      name: 'Bonaire, Sint Eustatius and Saba',
      a2: 'BQ',
      a3: 'BES',
      num: '535',
      itu: 'ATN',
      gec: 'NL',
      ioc: 'AHO',
      fifa: 'ANT',
      ds: 'NA',
      wmo: 'NU',
      gaul: '176',
      marc: 'ca',
      dial: '599',
      independent: 'Part of NL',
    ),
    Country(
      name: 'Bosnia and Herzegovina',
      a2: 'BA',
      a3: 'BIH',
      num: '70',
      itu: 'BIH',
      gec: 'BK',
      ioc: 'BIH',
      fifa: 'BIH',
      ds: 'BIH',
      wmo: 'BG',
      gaul: '34',
      marc: 'bn',
      dial: '387',
      independent: 'Yes',
    ),
    Country(
      name: 'Botswana',
      a2: 'BW',
      a3: 'BWA',
      num: '72',
      itu: 'BOT',
      gec: 'BC',
      ioc: 'BOT',
      fifa: 'BOT',
      ds: 'BW',
      wmo: 'BC',
      gaul: '35',
      marc: 'bs',
      dial: '267',
      independent: 'Yes',
    ),
    Country(
      name: 'Bouvet Island',
      a2: 'BV',
      a3: 'BVT',
      num: '74',
      gec: 'BV',
      ds: 'BV',
      wmo: 'BV',
      gaul: '36',
      marc: 'bv',
      dial: '47',
      independent: 'Territory of NO',
    ),
    Country(
      name: 'Brazil',
      a2: 'BR',
      a3: 'BRA',
      num: '76',
      itu: 'B',
      gec: 'BR',
      ioc: 'BRA',
      fifa: 'BRA',
      ds: 'BR',
      wmo: 'BZ',
      gaul: '37',
      marc: 'bl',
      dial: '55',
      independent: 'Yes',
    ),
    Country(
      name: 'British Indian Ocean Territory',
      a2: 'IO',
      a3: 'IOT',
      num: '86',
      itu: 'BIO',
      gec: 'IO',
      gaul: '38',
      marc: 'bi',
      dial: '246',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Brunei Darussalam',
      a2: 'BN',
      a3: 'BRN',
      num: '96',
      itu: 'BRU',
      gec: 'BX',
      ioc: 'BRU',
      fifa: 'BRU',
      ds: 'BRU',
      wmo: 'BD',
      gaul: '40',
      marc: 'bx',
      dial: '673',
      independent: 'Yes',
    ),
    Country(
      name: 'Bulgaria',
      a2: 'BG',
      a3: 'BGR',
      num: '100',
      itu: 'BUL',
      gec: 'BU',
      ioc: 'BUL',
      fifa: 'BUL',
      ds: 'BG',
      wmo: 'BU',
      gaul: '41',
      marc: 'bu',
      dial: '359',
      independent: 'Yes',
    ),
    Country(
      name: 'Burkina Faso',
      a2: 'BF',
      a3: 'BFA',
      num: '854',
      itu: 'BFA',
      gec: 'UV',
      ioc: 'BUR',
      fifa: 'BFA',
      ds: 'BF',
      wmo: 'HV',
      gaul: '42',
      marc: 'uv',
      dial: '226',
      independent: 'Yes',
    ),
    Country(
      name: 'Burundi',
      a2: 'BI',
      a3: 'BDI',
      num: '108',
      itu: 'BDI',
      gec: 'BY',
      ioc: 'BDI',
      fifa: 'BDI',
      ds: 'RU',
      wmo: 'BI',
      gaul: '43',
      marc: 'bd',
      dial: '257',
      independent: 'Yes',
    ),
    Country(
      name: 'Cambodia',
      a2: 'KH',
      a3: 'KHM',
      num: '116',
      itu: 'CBG',
      gec: 'CB',
      ioc: 'CAM',
      fifa: 'CAM',
      ds: 'K',
      wmo: 'KP',
      gaul: '44',
      marc: 'cb',
      dial: '855',
      independent: 'Yes',
    ),
    Country(
      name: 'Cameroon',
      a2: 'CM',
      a3: 'CMR',
      num: '120',
      itu: 'CME',
      gec: 'CM',
      ioc: 'CMR',
      fifa: 'CMR',
      ds: 'CAM',
      wmo: 'CM',
      gaul: '45',
      marc: 'cm',
      dial: '237',
      independent: 'Yes',
    ),
    Country(
      name: 'Canada',
      a2: 'CA',
      a3: 'CAN',
      num: '124',
      itu: 'CAN',
      gec: 'CA',
      ioc: 'CAN',
      fifa: 'CAN',
      ds: 'CDN',
      wmo: 'CN',
      gaul: '46',
      marc: 'xxc',
      dial: '1',
      independent: 'Yes',
    ),
    Country(
      name: 'Cape Verde',
      a2: 'CV',
      a3: 'CPV',
      num: '132',
      itu: 'CPV',
      gec: 'CV',
      ioc: 'CPV',
      fifa: 'CPV',
      ds: 'CV',
      wmo: 'CV',
      gaul: '47',
      marc: 'cv',
      dial: '238',
      independent: 'Yes',
    ),
    Country(
      name: 'Cayman Islands',
      a2: 'KY',
      a3: 'CYM',
      num: '136',
      itu: 'CYM',
      gec: 'CJ',
      ioc: 'CAY',
      fifa: 'CAY',
      ds: 'KY',
      wmo: 'GC',
      gaul: '48',
      marc: 'cj',
      dial: '1-345',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Central African Republic',
      a2: 'CF',
      a3: 'CAF',
      num: '140',
      itu: 'CAF',
      gec: 'CT',
      ioc: 'CAF',
      fifa: 'CTA',
      ds: 'RCA',
      wmo: 'CE',
      gaul: '49',
      marc: 'cx',
      dial: '236',
      independent: 'Yes',
    ),
    Country(
      name: 'Chad',
      a2: 'TD',
      a3: 'TCD',
      num: '148',
      itu: 'TCD',
      gec: 'CD',
      ioc: 'CHA',
      fifa: 'CHA',
      ds: 'TCH',
      wmo: 'CD',
      gaul: '50',
      marc: 'cd',
      dial: '235',
      independent: 'Yes',
    ),
    Country(
      name: 'Chile',
      a2: 'CL',
      a3: 'CHL',
      num: '152',
      itu: 'CHL',
      gec: 'CI',
      ioc: 'CHI',
      fifa: 'CHI',
      ds: 'RCH',
      wmo: 'CH',
      gaul: '51',
      marc: 'cl',
      dial: '56',
      independent: 'Yes',
    ),
    Country(
      name: 'China',
      a2: 'CN',
      a3: 'CHN',
      num: '156',
      itu: 'CHN',
      gec: 'CH',
      ioc: 'CHN',
      fifa: 'CHN',
      ds: 'CN',
      wmo: 'CI',
      gaul: '53',
      marc: 'cc',
      dial: '86',
      independent: 'Yes',
    ),
    Country(
      name: 'Christmas Island',
      a2: 'CX',
      a3: 'CXR',
      num: '162',
      itu: 'CHR',
      gec: 'KT',
      fifa: 'CXR',
      ds: 'AUS',
      wmo: 'KI',
      gaul: '54',
      marc: 'xa',
      dial: '61',
      independent: 'Territory of AU',
    ),
    Country(
      name: 'Cocos (Keeling) Islands',
      a2: 'CC',
      a3: 'CCK',
      num: '166',
      itu: 'ICO',
      gec: 'CK',
      fifa: 'CCK',
      ds: 'AUS',
      wmo: 'KK',
      gaul: '56',
      marc: 'xb',
      dial: '61',
      independent: 'Territory of AU',
    ),
    Country(
      name: 'Colombia',
      a2: 'CO',
      a3: 'COL',
      num: '170',
      itu: 'CLM',
      gec: 'CO',
      ioc: 'COL',
      fifa: 'COL',
      ds: 'CO',
      wmo: 'CO',
      gaul: '57',
      marc: 'ck',
      dial: '57',
      independent: 'Yes',
    ),
    Country(
      name: 'Comoros',
      a2: 'KM',
      a3: 'COM',
      num: '174',
      itu: 'COM',
      gec: 'CN',
      ioc: 'COM',
      fifa: 'COM',
      ds: 'KM',
      wmo: 'IC',
      gaul: '58',
      marc: 'cq',
      dial: '269',
      independent: 'Yes',
    ),
    Country(
      name: 'Congo (Brazzaville)',
      a2: 'CG',
      a3: 'COG',
      num: '178',
      itu: 'COG',
      gec: 'CF',
      ioc: 'CGO',
      fifa: 'CGO',
      ds: 'RCB',
      wmo: 'CG',
      gaul: '59',
      marc: 'cf',
      dial: '242',
      independent: 'Yes',
    ),
    Country(
      name: 'Congo (Kinshasa)',
      a2: 'CD',
      a3: 'COD',
      num: '180',
      itu: 'COD',
      gec: 'CG',
      ioc: 'COD',
      fifa: 'COD',
      ds: 'ZRE',
      wmo: 'ZR',
      gaul: '68',
      marc: 'cg',
      dial: '243',
      independent: 'Yes',
    ),
    Country(
      name: 'Cook Islands',
      a2: 'CK',
      a3: 'COK',
      num: '184',
      itu: 'CKH',
      gec: 'CW',
      ioc: 'COK',
      fifa: 'COK',
      ds: 'NZ',
      wmo: 'KU',
      gaul: '60',
      marc: 'cw',
      dial: '682',
      independent: 'Associated with NZ',
    ),
    Country(
      name: 'Costa Rica',
      a2: 'CR',
      a3: 'CRI',
      num: '188',
      itu: 'CTR',
      gec: 'CS',
      ioc: 'CRC',
      fifa: 'CRC',
      ds: 'CR',
      wmo: 'CS',
      gaul: '61',
      marc: 'cr',
      dial: '506',
      independent: 'Yes',
    ),
    Country(
      name: 'Côte d\'Ivoire',
      a2: 'CI',
      a3: 'CIV',
      num: '384',
      itu: 'CTI',
      gec: 'IV',
      ioc: 'CIV',
      fifa: 'CIV',
      ds: 'CI',
      wmo: 'IV',
      gaul: '66',
      marc: 'iv',
      dial: '225',
      independent: 'Yes',
    ),
    Country(
      name: 'Croatia',
      a2: 'HR',
      a3: 'HRV',
      num: '191',
      itu: 'HRV',
      gec: 'HR',
      ioc: 'CRO',
      fifa: 'CRO',
      ds: 'HR',
      wmo: 'RH',
      gaul: '62',
      marc: 'ci',
      dial: '385',
      independent: 'Yes',
    ),
    Country(
      name: 'Cuba',
      a2: 'CU',
      a3: 'CUB',
      num: '192',
      itu: 'CUB',
      gec: 'CU',
      ioc: 'CUB',
      fifa: 'CUB',
      ds: 'C',
      wmo: 'CU',
      gaul: '63',
      marc: 'cu',
      dial: '53',
      independent: 'Yes',
    ),
    Country(
      name: 'Curaçao',
      a2: 'CW',
      a3: 'CUW',
      num: '531',
      gec: 'UC',
      marc: 'co',
      dial: '599',
      independent: 'Part of NL',
    ),
    Country(
      name: 'Cyprus',
      a2: 'CY',
      a3: 'CYP',
      num: '196',
      itu: 'CYP',
      gec: 'CY',
      ioc: 'CYP',
      fifa: 'CYP',
      ds: 'CY',
      wmo: 'CY',
      gaul: '64',
      marc: 'cy',
      dial: '357',
      independent: 'Yes',
    ),
    Country(
      name: 'Czech Republic',
      a2: 'CZ',
      a3: 'CZE',
      num: '203',
      itu: 'CZE',
      gec: 'EZ',
      ioc: 'CZE',
      fifa: 'CZE',
      ds: 'CZ',
      wmo: 'CZ',
      gaul: '65',
      marc: 'xr',
      dial: '420',
      independent: 'Yes',
    ),
    Country(
      name: 'Denmark',
      a2: 'DK',
      a3: 'DNK',
      num: '208',
      itu: 'DNK',
      gec: 'DA',
      ioc: 'DEN',
      fifa: 'DEN',
      ds: 'DK',
      wmo: 'DN',
      gaul: '69',
      marc: 'dk',
      dial: '45',
      independent: 'Yes',
    ),
    Country(
      name: 'Djibouti',
      a2: 'DJ',
      a3: 'DJI',
      num: '262',
      itu: 'DJI',
      gec: 'DJ',
      ioc: 'DJI',
      fifa: 'DJI',
      ds: 'F',
      wmo: 'DJ',
      gaul: '70',
      marc: 'ft',
      dial: '253',
      independent: 'Yes',
    ),
    Country(
      name: 'Dominica',
      a2: 'DM',
      a3: 'DMA',
      num: '212',
      itu: 'DMA',
      gec: 'DO',
      ioc: 'DMA',
      fifa: 'DMA',
      ds: 'WD',
      wmo: 'DO',
      gaul: '71',
      marc: 'dq',
      dial: '1-767',
      independent: 'Yes',
    ),
    Country(
      name: 'Dominican Republic',
      a2: 'DO',
      a3: 'DOM',
      num: '214',
      itu: 'DOM',
      gec: 'DR',
      ioc: 'DOM',
      fifa: 'DOM',
      ds: 'DOM',
      wmo: 'DR',
      gaul: '72',
      marc: 'dr',
      dial: '1-809, 1-829, 1-849',
      independent: 'Yes',
    ),
    Country(
      name: 'Ecuador',
      a2: 'EC',
      a3: 'ECU',
      num: '218',
      itu: 'EQA',
      gec: 'EC',
      ioc: 'ECU',
      fifa: 'ECU',
      ds: 'EC',
      wmo: 'EQ',
      gaul: '73',
      marc: 'ec',
      dial: '593',
      independent: 'Yes',
    ),
    Country(
      name: 'Egypt',
      a2: 'EG',
      a3: 'EGY',
      num: '818',
      itu: 'EGY',
      gec: 'EG',
      ioc: 'EGY',
      fifa: 'EGY',
      ds: 'ET',
      wmo: 'EG',
      gaul: '40765',
      marc: 'ua',
      dial: '20',
      independent: 'Yes',
    ),
    Country(
      name: 'El Salvador',
      a2: 'SV',
      a3: 'SLV',
      num: '222',
      itu: 'SLV',
      gec: 'ES',
      ioc: 'ESA',
      fifa: 'SLV',
      ds: 'ES',
      wmo: 'ES',
      gaul: '75',
      marc: 'es',
      dial: '503',
      independent: 'Yes',
    ),
    Country(
      name: 'Equatorial Guinea',
      a2: 'GQ',
      a3: 'GNQ',
      num: '226',
      itu: 'GNE',
      gec: 'EK',
      ioc: 'GEQ',
      fifa: 'EQG',
      ds: 'EQ',
      wmo: 'GQ',
      gaul: '76',
      marc: 'eg',
      dial: '240',
      independent: 'Yes',
    ),
    Country(
      name: 'Eritrea',
      a2: 'ER',
      a3: 'ERI',
      num: '232',
      itu: 'ERI',
      gec: 'ER',
      ioc: 'ERI',
      fifa: 'ERI',
      ds: 'ER',
      gaul: '77',
      marc: 'ea',
      dial: '291',
      independent: 'Yes',
    ),
    Country(
      name: 'Estonia',
      a2: 'EE',
      a3: 'EST',
      num: '233',
      itu: 'EST',
      gec: 'EN',
      ioc: 'EST',
      fifa: 'EST',
      ds: 'EST',
      wmo: 'EO',
      gaul: '78',
      marc: 'er',
      dial: '372',
      independent: 'Yes',
    ),
    Country(
      name: 'Ethiopia',
      a2: 'ET',
      a3: 'ETH',
      num: '231',
      itu: 'ETH',
      gec: 'ET',
      ioc: 'ETH',
      fifa: 'ETH',
      ds: 'ETH',
      wmo: 'ET',
      gaul: '79',
      marc: 'et',
      dial: '251',
      independent: 'Yes',
    ),
    Country(
      name: 'Falkland Islands',
      a2: 'FK',
      a3: 'FLK',
      num: '238',
      itu: 'FLK',
      gec: 'FK',
      ioc: 'FLK',
      fifa: 'FLK',
      wmo: 'FK',
      gaul: '81',
      marc: 'fk',
      dial: '500',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Faroe Islands',
      a2: 'FO',
      a3: 'FRO',
      num: '234',
      itu: 'FRO',
      gec: 'FO',
      ioc: 'FAR',
      fifa: 'FRO',
      ds: 'FO',
      wmo: 'FA',
      gaul: '82',
      marc: 'fa',
      dial: '298',
      independent: 'Part of DK',
    ),
    Country(
      name: 'Fiji',
      a2: 'FJ',
      a3: 'FJI',
      num: '242',
      itu: 'FJI',
      gec: 'FJ',
      ioc: 'FIJ',
      fifa: 'FIJ',
      ds: 'FJI',
      wmo: 'FJ',
      gaul: '83',
      marc: 'fj',
      dial: '679',
      independent: 'Yes',
    ),
    Country(
      name: 'Finland',
      a2: 'FI',
      a3: 'FIN',
      num: '246',
      itu: 'FIN',
      gec: 'FI',
      ioc: 'FIN',
      fifa: 'FIN',
      ds: 'FIN',
      wmo: 'FI',
      gaul: '84',
      marc: 'fi',
      dial: '358',
      independent: 'Yes',
    ),
    Country(
      name: 'France',
      a2: 'FR',
      a3: 'FRA',
      num: '250',
      itu: 'F',
      gec: 'FR',
      ioc: 'FRA',
      fifa: 'FRA',
      ds: 'F',
      wmo: 'FR',
      gaul: '85',
      marc: 'fr',
      dial: '33',
      independent: 'Yes',
    ),
    Country(
      name: 'French Guiana',
      a2: 'GF',
      a3: 'GUF',
      num: '254',
      itu: 'GUF',
      gec: 'FG',
      ioc: 'FGU',
      fifa: 'GUF',
      ds: 'F',
      wmo: 'FG',
      gaul: '86',
      marc: 'fg',
      dial: '594',
      independent: 'Part of FR',
    ),
    Country(
      name: 'French Polynesia',
      a2: 'PF',
      a3: 'PYF',
      num: '258',
      itu: 'OCE',
      gec: 'FP',
      ioc: 'FPO',
      fifa: 'TAH',
      ds: 'F',
      wmo: 'PF',
      gaul: '87',
      marc: 'fp',
      dial: '689',
      independent: 'Territory of FR',
    ),
    Country(
      name: 'French Southern Lands',
      a2: 'TF',
      a3: 'ATF',
      num: '260',
      gec: 'FS',
      ds: 'F',
      gaul: '88',
      marc: 'fs',
      dial: '262',
      independent: 'Territory of FR',
    ),
    Country(
      name: 'Gabon',
      a2: 'GA',
      a3: 'GAB',
      num: '266',
      itu: 'GAB',
      gec: 'GB',
      ioc: 'GAB',
      fifa: 'GAB',
      ds: 'G',
      wmo: 'GO',
      gaul: '89',
      marc: 'go',
      dial: '241',
      independent: 'Yes',
    ),
    Country(
      name: 'Gambia',
      a2: 'GM',
      a3: 'GMB',
      num: '270',
      itu: 'GMB',
      gec: 'GA',
      ioc: 'GAM',
      fifa: 'GAM',
      ds: 'WAG',
      wmo: 'GB',
      gaul: '90',
      marc: 'gm',
      dial: '220',
      independent: 'Yes',
    ),
    Country(
      name: 'Georgia',
      a2: 'GE',
      a3: 'GEO',
      num: '268',
      itu: 'GEO',
      gec: 'GG',
      ioc: 'GEO',
      fifa: 'GEO',
      ds: 'GE',
      wmo: 'GG',
      gaul: '92',
      marc: 'gs',
      dial: '995',
      independent: 'Yes',
    ),
    Country(
      name: 'Germany',
      a2: 'DE',
      a3: 'DEU',
      num: '276',
      itu: 'D',
      gec: 'GM',
      ioc: 'GER',
      fifa: 'GER',
      ds: 'D',
      wmo: 'DL',
      gaul: '93',
      marc: 'gw',
      dial: '49',
      independent: 'Yes',
    ),
    Country(
      name: 'Ghana',
      a2: 'GH',
      a3: 'GHA',
      num: '288',
      itu: 'GHA',
      gec: 'GH',
      ioc: 'GHA',
      fifa: 'GHA',
      ds: 'GH',
      wmo: 'GH',
      gaul: '94',
      marc: 'gh',
      dial: '233',
      independent: 'Yes',
    ),
    Country(
      name: 'Gibraltar',
      a2: 'GI',
      a3: 'GIB',
      num: '292',
      itu: 'GIB',
      gec: 'GI',
      ioc: 'GIB',
      fifa: 'GBZ',
      ds: 'GBZ',
      wmo: 'GI',
      gaul: '95',
      marc: 'gi',
      dial: '350',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Greece',
      a2: 'GR',
      a3: 'GRC',
      num: '300',
      itu: 'GRC',
      gec: 'GR',
      ioc: 'GRE',
      fifa: 'GRE',
      ds: 'GR',
      wmo: 'GR',
      gaul: '97',
      marc: 'gr',
      dial: '30',
      independent: 'Yes',
    ),
    Country(
      name: 'Greenland',
      a2: 'GL',
      a3: 'GRL',
      num: '304',
      itu: 'GRL',
      gec: 'GL',
      ioc: 'GRL',
      fifa: 'GRL',
      ds: 'DK',
      wmo: 'GL',
      gaul: '98',
      marc: 'gl',
      dial: '299',
      independent: 'Part of DK',
    ),
    Country(
      name: 'Grenada',
      a2: 'GD',
      a3: 'GRD',
      num: '308',
      itu: 'GRD',
      gec: 'GJ',
      ioc: 'GRN',
      fifa: 'GRN',
      ds: 'WG',
      wmo: 'GD',
      gaul: '99',
      marc: 'gd',
      dial: '1-473',
      independent: 'Yes',
    ),
    Country(
      name: 'Guadeloupe',
      a2: 'GP',
      a3: 'GLP',
      num: '312',
      itu: 'GDL',
      gec: 'GP',
      ioc: 'GUD',
      fifa: 'GLP',
      ds: 'F',
      wmo: 'MF',
      gaul: '100',
      marc: 'gp',
      dial: '590',
      independent: 'Part of FR',
    ),
    Country(
      name: 'Guam',
      a2: 'GU',
      a3: 'GUM',
      num: '316',
      itu: 'GUM',
      gec: 'GQ',
      ioc: 'GUM',
      fifa: 'GUM',
      ds: 'USA',
      wmo: 'GM',
      gaul: '101',
      marc: 'gu',
      dial: '1-671',
      independent: 'Territory of US',
    ),
    Country(
      name: 'Guatemala',
      a2: 'GT',
      a3: 'GTM',
      num: '320',
      itu: 'GTM',
      gec: 'GT',
      ioc: 'GUA',
      fifa: 'GUA',
      ds: 'GCA',
      wmo: 'GU',
      gaul: '103',
      marc: 'gt',
      dial: '502',
      independent: 'Yes',
    ),
    Country(
      name: 'Guernsey',
      a2: 'GG',
      a3: 'GGY',
      num: '831',
      gec: 'GK',
      fifa: 'GBG',
      ds: 'GBG',
      gaul: '104',
      marc: 'uik',
      dial: '44',
      independent: 'Crown dependency of GB',
    ),
    Country(
      name: 'Guinea',
      a2: 'GN',
      a3: 'GIN',
      num: '324',
      itu: 'GUI',
      gec: 'GV',
      ioc: 'GUI',
      fifa: 'GUI',
      ds: 'RG',
      wmo: 'GN',
      gaul: '106',
      marc: 'gv',
      dial: '224',
      independent: 'Yes',
    ),
    Country(
      name: 'Guinea-Bissau',
      a2: 'GW',
      a3: 'GNB',
      num: '624',
      itu: 'GNB',
      gec: 'PU',
      ioc: 'GBS',
      fifa: 'GNB',
      ds: 'GW',
      wmo: 'GW',
      gaul: '105',
      marc: 'pg',
      dial: '245',
      independent: 'Yes',
    ),
    Country(
      name: 'Guyana',
      a2: 'GY',
      a3: 'GUY',
      num: '328',
      itu: 'GUY',
      gec: 'GY',
      ioc: 'GUY',
      fifa: 'GUY',
      ds: 'GUY',
      wmo: 'GY',
      gaul: '107',
      marc: 'gy',
      dial: '592',
      independent: 'Yes',
    ),
    Country(
      name: 'Haiti',
      a2: 'HT',
      a3: 'HTI',
      num: '332',
      itu: 'HTI',
      gec: 'HA',
      ioc: 'HAI',
      fifa: 'HAI',
      ds: 'RH',
      wmo: 'HA',
      gaul: '108',
      marc: 'ht',
      dial: '509',
      independent: 'Yes',
    ),
    Country(
      name: 'Heard and McDonald Islands',
      a2: 'HM',
      a3: 'HMD',
      num: '334',
      gec: 'HM',
      ds: 'AUS',
      gaul: '109',
      marc: 'hm',
      dial: '672',
      independent: 'Territory of AU',
    ),
    Country(
      name: 'Honduras',
      a2: 'HN',
      a3: 'HND',
      num: '340',
      itu: 'HND',
      gec: 'HO',
      ioc: 'HON',
      fifa: 'HON',
      wmo: 'HO',
      gaul: '111',
      marc: 'ho',
      dial: '504',
      independent: 'Yes',
    ),
    Country(
      name: 'Hong Kong',
      a2: 'HK',
      a3: 'HKG',
      num: '344',
      itu: 'HKG',
      gec: 'HK',
      ioc: 'HKG',
      fifa: 'HKG',
      ds: 'HK',
      wmo: 'HK',
      gaul: '33364',
      dial: '852',
      independent: 'Part of CN',
    ),
    Country(
      name: 'Hungary',
      a2: 'HU',
      a3: 'HUN',
      num: '348',
      itu: 'HNG',
      gec: 'HU',
      ioc: 'HUN',
      fifa: 'HUN',
      ds: 'H',
      wmo: 'HU',
      gaul: '113',
      marc: 'hu',
      dial: '36',
      independent: 'Yes',
    ),
    Country(
      name: 'Iceland',
      a2: 'IS',
      a3: 'ISL',
      num: '352',
      itu: 'ISL',
      gec: 'IC',
      ioc: 'ISL',
      fifa: 'ISL',
      ds: 'IS',
      wmo: 'IL',
      gaul: '114',
      marc: 'ic',
      dial: '354',
      independent: 'Yes',
    ),
    Country(
      name: 'India',
      a2: 'IN',
      a3: 'IND',
      num: '356',
      itu: 'IND',
      gec: 'IN',
      ioc: 'IND',
      fifa: 'IND',
      ds: 'IND',
      wmo: 'IN',
      gaul: '115',
      marc: 'ii',
      dial: '91',
      independent: 'Yes',
    ),
    Country(
      name: 'Indonesia',
      a2: 'ID',
      a3: 'IDN',
      num: '360',
      itu: 'INS',
      gec: 'ID',
      ioc: 'INA',
      fifa: 'IDN',
      ds: 'RI',
      wmo: 'ID',
      gaul: '116',
      marc: 'io',
      dial: '62',
      independent: 'Yes',
    ),
    Country(
      name: 'Iran',
      a2: 'IR',
      a3: 'IRN',
      num: '364',
      itu: 'IRN',
      gec: 'IR',
      ioc: 'IRI',
      fifa: 'IRN',
      ds: 'IR',
      wmo: 'IR',
      gaul: '117',
      marc: 'ir',
      dial: '98',
      independent: 'Yes',
    ),
    Country(
      name: 'Iraq',
      a2: 'IQ',
      a3: 'IRQ',
      num: '368',
      itu: 'IRQ',
      gec: 'IZ',
      ioc: 'IRQ',
      fifa: 'IRQ',
      ds: 'IRQ',
      wmo: 'IQ',
      gaul: '118',
      marc: 'iq',
      dial: '964',
      independent: 'Yes',
    ),
    Country(
      name: 'Ireland',
      a2: 'IE',
      a3: 'IRL',
      num: '372',
      itu: 'IRL',
      gec: 'EI',
      ioc: 'IRL',
      fifa: 'IRL',
      ds: 'IRL',
      wmo: 'IE',
      gaul: '119',
      marc: 'ie',
      dial: '353',
      independent: 'Yes',
    ),
    Country(
      name: 'Isle of Man',
      a2: 'IM',
      a3: 'IMN',
      num: '833',
      gec: 'IM',
      fifa: 'GBM',
      ds: 'GBM',
      gaul: '120',
      marc: 'uik',
      dial: '44',
      independent: 'Crown dependency of GB',
    ),
    Country(
      name: 'Israel',
      a2: 'IL',
      a3: 'ISR',
      num: '376',
      itu: 'ISR',
      gec: 'IS',
      ioc: 'ISR',
      fifa: 'ISR',
      ds: 'IL',
      wmo: 'IS',
      gaul: '121',
      marc: 'is',
      dial: '972',
      independent: 'Yes',
    ),
    Country(
      name: 'Italy',
      a2: 'IT',
      a3: 'ITA',
      num: '380',
      itu: 'I',
      gec: 'IT',
      ioc: 'ITA',
      fifa: 'ITA',
      ds: 'I',
      wmo: 'IY',
      gaul: '122',
      marc: 'it',
      dial: '39',
      independent: 'Yes',
    ),
    Country(
      name: 'Jamaica',
      a2: 'JM',
      a3: 'JAM',
      num: '388',
      itu: 'JMC',
      gec: 'JM',
      ioc: 'JAM',
      fifa: 'JAM',
      ds: 'JA',
      wmo: 'JM',
      gaul: '123',
      marc: 'jm',
      dial: '1-876',
      independent: 'Yes',
    ),
    Country(
      name: 'Japan',
      a2: 'JP',
      a3: 'JPN',
      num: '392',
      itu: 'J',
      gec: 'JA',
      ioc: 'JPN',
      fifa: 'JPN',
      ds: 'J',
      wmo: 'JP',
      gaul: '126',
      marc: 'ja',
      dial: '81',
      independent: 'Yes',
    ),
    Country(
      name: 'Jersey',
      a2: 'JE',
      a3: 'JEY',
      num: '832',
      gec: 'JE',
      fifa: 'GBJ',
      ds: 'GBJ',
      gaul: '128',
      marc: 'uik',
      dial: '44',
      independent: 'Crown dependency of GB',
    ),
    Country(
      name: 'Jordan',
      a2: 'JO',
      a3: 'JOR',
      num: '400',
      itu: 'JOR',
      gec: 'JO',
      ioc: 'JOR',
      fifa: 'JOR',
      ds: 'HKJ',
      wmo: 'JD',
      gaul: '130',
      marc: 'jo',
      dial: '962',
      independent: 'Yes',
    ),
    Country(
      name: 'Kazakhstan',
      a2: 'KZ',
      a3: 'KAZ',
      num: '398',
      itu: 'KAZ',
      gec: 'KZ',
      ioc: 'KAZ',
      fifa: 'KAZ',
      ds: 'KZ',
      wmo: 'KZ',
      gaul: '132',
      marc: 'kz',
      dial: '7',
      independent: 'Yes',
    ),
    Country(
      name: 'Kenya',
      a2: 'KE',
      a3: 'KEN',
      num: '404',
      itu: 'KEN',
      gec: 'KE',
      ioc: 'KEN',
      fifa: 'KEN',
      ds: 'EAK',
      wmo: 'KN',
      gaul: '133',
      marc: 'ke',
      dial: '254',
      independent: 'Yes',
    ),
    Country(
      name: 'Kiribati',
      a2: 'KI',
      a3: 'KIR',
      num: '296',
      itu: 'KIR',
      gec: 'KR',
      ioc: 'KIR',
      fifa: 'KIR',
      wmo: 'KB',
      gaul: '135',
      marc: 'gb',
      dial: '686',
      independent: 'Yes',
    ),
    Country(
      name: 'North Korea',
      a2: 'KP',
      a3: 'PRK',
      num: '408',
      itu: 'KRE',
      gec: 'KN',
      ioc: 'PRK',
      fifa: 'PRK',
      wmo: 'KR',
      gaul: '67',
      marc: 'kn',
      dial: '850',
      independent: 'Yes',
    ),
    Country(
      name: 'South Korea',
      a2: 'KR',
      a3: 'KOR',
      num: '410',
      itu: 'KOR',
      gec: 'KS',
      ioc: 'KOR',
      fifa: 'KOR',
      ds: 'ROK',
      wmo: 'KO',
      gaul: '202',
      marc: 'ko',
      dial: '82',
      independent: 'Yes',
    ),
    Country(
      name: 'Kuwait',
      a2: 'KW',
      a3: 'KWT',
      num: '414',
      itu: 'KWT',
      gec: 'KU',
      ioc: 'KUW',
      fifa: 'KUW',
      ds: 'KWT',
      wmo: 'KW',
      gaul: '137',
      marc: 'ku',
      dial: '965',
      independent: 'Yes',
    ),
    Country(
      name: 'Kyrgyzstan',
      a2: 'KG',
      a3: 'KGZ',
      num: '417',
      itu: 'KGZ',
      gec: 'KG',
      ioc: 'KGZ',
      fifa: 'KGZ',
      ds: 'KS',
      wmo: 'KG',
      gaul: '138',
      marc: 'kg',
      dial: '996',
      independent: 'Yes',
    ),
    Country(
      name: 'Laos',
      a2: 'LA',
      a3: 'LAO',
      num: '418',
      itu: 'LAO',
      gec: 'LA',
      ioc: 'LAO',
      fifa: 'LAO',
      ds: 'LAO',
      wmo: 'LA',
      gaul: '139',
      marc: 'ls',
      dial: '856',
      independent: 'Yes',
    ),
    Country(
      name: 'Latvia',
      a2: 'LV',
      a3: 'LVA',
      num: '428',
      itu: 'LVA',
      gec: 'LG',
      ioc: 'LAT',
      fifa: 'LVA',
      ds: 'LV',
      wmo: 'LV',
      gaul: '140',
      marc: 'lv',
      dial: '371',
      independent: 'Yes',
    ),
    Country(
      name: 'Lebanon',
      a2: 'LB',
      a3: 'LBN',
      num: '422',
      itu: 'LBN',
      gec: 'LE',
      ioc: 'LIB',
      fifa: 'LIB',
      ds: 'RL',
      wmo: 'LB',
      gaul: '141',
      marc: 'le',
      dial: '961',
      independent: 'Yes',
    ),
    Country(
      name: 'Lesotho',
      a2: 'LS',
      a3: 'LSO',
      num: '426',
      itu: 'LSO',
      gec: 'LT',
      ioc: 'LES',
      fifa: 'LES',
      ds: 'LS',
      wmo: 'LS',
      gaul: '142',
      marc: 'lo',
      dial: '266',
      independent: 'Yes',
    ),
    Country(
      name: 'Liberia',
      a2: 'LR',
      a3: 'LBR',
      num: '430',
      itu: 'LBR',
      gec: 'LI',
      ioc: 'LBR',
      fifa: 'LBR',
      ds: 'LB',
      wmo: 'LI',
      gaul: '144',
      marc: 'lb',
      dial: '231',
      independent: 'Yes',
    ),
    Country(
      name: 'Libya',
      a2: 'LY',
      a3: 'LBY',
      num: '434',
      itu: 'LBY',
      gec: 'LY',
      ioc: 'LBA',
      fifa: 'LBY',
      ds: 'LAR',
      wmo: 'LY',
      gaul: '145',
      marc: 'ly',
      dial: '218',
      independent: 'Yes',
    ),
    Country(
      name: 'Liechtenstein',
      a2: 'LI',
      a3: 'LIE',
      num: '438',
      itu: 'LIE',
      gec: 'LS',
      ioc: 'LIE',
      fifa: 'LIE',
      ds: 'FL',
      gaul: '146',
      marc: 'lh',
      dial: '423',
      independent: 'Yes',
    ),
    Country(
      name: 'Lithuania',
      a2: 'LT',
      a3: 'LTU',
      num: '440',
      itu: 'LTU',
      gec: 'LH',
      ioc: 'LTU',
      fifa: 'LTU',
      ds: 'LT',
      wmo: 'LT',
      gaul: '147',
      marc: 'li',
      dial: '370',
      independent: 'Yes',
    ),
    Country(
      name: 'Luxembourg',
      a2: 'LU',
      a3: 'LUX',
      num: '442',
      itu: 'LUX',
      gec: 'LU',
      ioc: 'LUX',
      fifa: 'LUX',
      ds: 'L',
      wmo: 'BX',
      gaul: '148',
      marc: 'lu',
      dial: '352',
      independent: 'Yes',
    ),
    Country(
      name: 'Macau',
      a2: 'MO',
      a3: 'MAC',
      num: '446',
      itu: 'MAC',
      gec: 'MC',
      ioc: 'MAC',
      fifa: 'MAC',
      ds: 'MO',
      wmo: 'MU',
      gaul: '149',
      dial: '853',
      independent: 'Part of CN',
    ),
    Country(
      name: 'Macedonia',
      a2: 'MK',
      a3: 'MKD',
      num: '807',
      itu: 'MKD',
      gec: 'MK',
      ioc: 'MKD',
      fifa: 'MKD',
      ds: 'MK',
      wmo: 'MJ',
      gaul: '241',
      marc: 'xn',
      dial: '389',
      independent: 'Yes',
    ),
    Country(
      name: 'Madagascar',
      a2: 'MG',
      a3: 'MDG',
      num: '450',
      itu: 'MDG',
      gec: 'MA',
      ioc: 'MAD',
      fifa: 'MAD',
      ds: 'RM',
      wmo: 'MG',
      gaul: '150',
      marc: 'mg',
      dial: '261',
      independent: 'Yes',
    ),
    Country(
      name: 'Malawi',
      a2: 'MW',
      a3: 'MWI',
      num: '454',
      itu: 'MWI',
      gec: 'MI',
      ioc: 'MAW',
      fifa: 'MWI',
      ds: 'MW',
      wmo: 'MW',
      gaul: '152',
      marc: 'mw',
      dial: '265',
      independent: 'Yes',
    ),
    Country(
      name: 'Malaysia',
      a2: 'MY',
      a3: 'MYS',
      num: '458',
      itu: 'MLA',
      gec: 'MY',
      ioc: 'MAS',
      fifa: 'MAS',
      ds: 'MAL',
      wmo: 'MS',
      gaul: '153',
      marc: 'my',
      dial: '60',
      independent: 'Yes',
    ),
    Country(
      name: 'Maldives',
      a2: 'MV',
      a3: 'MDV',
      num: '462',
      itu: 'MLD',
      gec: 'MV',
      ioc: 'MDV',
      fifa: 'MDV',
      ds: 'MV',
      wmo: 'MV',
      gaul: '154',
      marc: 'xc',
      dial: '960',
      independent: 'Yes',
    ),
    Country(
      name: 'Mali',
      a2: 'ML',
      a3: 'MLI',
      num: '466',
      itu: 'MLI',
      gec: 'ML',
      ioc: 'MLI',
      fifa: 'MLI',
      ds: 'RMM',
      wmo: 'MI',
      gaul: '155',
      marc: 'ml',
      dial: '223',
      independent: 'Yes',
    ),
    Country(
      name: 'Malta',
      a2: 'MT',
      a3: 'MLT',
      num: '470',
      itu: 'MLT',
      gec: 'MT',
      ioc: 'MLT',
      fifa: 'MLT',
      ds: 'M',
      wmo: 'ML',
      gaul: '156',
      marc: 'mm',
      dial: '356',
      independent: 'Yes',
    ),
    Country(
      name: 'Marshall Islands',
      a2: 'MH',
      a3: 'MHL',
      num: '584',
      itu: 'MHL',
      gec: 'RM',
      ioc: 'MSH',
      fifa: 'MHL',
      wmo: 'MH',
      gaul: '157',
      marc: 'xe',
      dial: '692',
      independent: 'Yes',
    ),
    Country(
      name: 'Martinique',
      a2: 'MQ',
      a3: 'MTQ',
      num: '474',
      itu: 'MRT',
      gec: 'MB',
      ioc: 'MRT',
      fifa: 'MTQ',
      ds: 'F',
      wmo: 'MR',
      gaul: '158',
      marc: 'mq',
      dial: '596',
      independent: 'Part of FR',
    ),
    Country(
      name: 'Mauritania',
      a2: 'MR',
      a3: 'MRT',
      num: '478',
      itu: 'MTN',
      gec: 'MR',
      ioc: 'MTN',
      fifa: 'MTN',
      ds: 'RIM',
      wmo: 'MT',
      gaul: '159',
      marc: 'mu',
      dial: '222',
      independent: 'Yes',
    ),
    Country(
      name: 'Mauritius',
      a2: 'MU',
      a3: 'MUS',
      num: '480',
      itu: 'MAU',
      gec: 'MP',
      ioc: 'MRI',
      fifa: 'MRI',
      ds: 'MS',
      wmo: 'MA',
      gaul: '160',
      marc: 'mf',
      dial: '230',
      independent: 'Yes',
    ),
    Country(
      name: 'Mayotte',
      a2: 'YT',
      a3: 'MYT',
      num: '175',
      itu: 'MYT',
      gec: 'MF',
      ioc: 'MAY',
      fifa: 'MYT',
      gaul: '161',
      marc: 'ot',
      dial: '262',
      independent: 'Part of FR',
    ),
    Country(
      name: 'Mexico',
      a2: 'MX',
      a3: 'MEX',
      num: '484',
      itu: 'MEX',
      gec: 'MX',
      ioc: 'MEX',
      fifa: 'MEX',
      ds: 'MEX',
      wmo: 'MX',
      gaul: '162',
      marc: 'mx',
      dial: '52',
      independent: 'Yes',
    ),
    Country(
      name: 'Micronesia',
      a2: 'FM',
      a3: 'FSM',
      num: '583',
      itu: 'FSM',
      gec: 'FM',
      ioc: 'FSM',
      fifa: 'FSM',
      gaul: '163',
      marc: 'fm',
      dial: '691',
      independent: 'Yes',
    ),
    Country(
      name: 'Moldova',
      a2: 'MD',
      a3: 'MDA',
      num: '498',
      itu: 'MDA',
      gec: 'MD',
      ioc: 'MDA',
      fifa: 'MDA',
      ds: 'MD',
      wmo: 'RM',
      gaul: '165',
      marc: 'mv',
      dial: '373',
      independent: 'Yes',
    ),
    Country(
      name: 'Monaco',
      a2: 'MC',
      a3: 'MCO',
      num: '492',
      itu: 'MCO',
      gec: 'MN',
      ioc: 'MON',
      fifa: 'MON',
      ds: 'MC',
      gaul: '166',
      marc: 'mc',
      dial: '377',
      independent: 'Yes',
    ),
    Country(
      name: 'Mongolia',
      a2: 'MN',
      a3: 'MNG',
      num: '496',
      itu: 'MNG',
      gec: 'MG',
      ioc: 'MGL',
      fifa: 'MNG',
      ds: 'MGL',
      wmo: 'MO',
      gaul: '167',
      marc: 'mp',
      dial: '976',
      independent: 'Yes',
    ),
    Country(
      name: 'Montenegro',
      a2: 'ME',
      a3: 'MNE',
      num: '499',
      itu: 'MNE',
      gec: 'MJ',
      ioc: 'MGO',
      fifa: 'MNE',
      ds: 'MNE',
      gaul: '2647',
      marc: 'mo',
      dial: '382',
      independent: 'Yes',
    ),
    Country(
      name: 'Montserrat',
      a2: 'MS',
      a3: 'MSR',
      num: '500',
      itu: 'MSR',
      gec: 'MH',
      ioc: 'MNT',
      fifa: 'MSR',
      gaul: '168',
      marc: 'mj',
      dial: '1-664',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Morocco',
      a2: 'MA',
      a3: 'MAR',
      num: '504',
      itu: 'MRC',
      gec: 'MO',
      ioc: 'MAR',
      fifa: 'MAR',
      ds: 'MA',
      wmo: 'MC',
      gaul: '169',
      marc: 'mr',
      dial: '212',
      independent: 'Yes',
    ),
    Country(
      name: 'Mozambique',
      a2: 'MZ',
      a3: 'MOZ',
      num: '508',
      itu: 'MOZ',
      gec: 'MZ',
      ioc: 'MOZ',
      fifa: 'MOZ',
      ds: 'MOC',
      wmo: 'MZ',
      gaul: '170',
      marc: 'mz',
      dial: '258',
      independent: 'Yes',
    ),
    Country(
      name: 'Myanmar',
      a2: 'MM',
      a3: 'MMR',
      num: '104',
      itu: 'MYA',
      gec: 'BM',
      ioc: 'MYA',
      fifa: 'MYA',
      ds: 'BUR',
      wmo: 'BM',
      gaul: '171',
      marc: 'br',
      dial: '95',
      independent: 'Yes',
    ),
    Country(
      name: 'Namibia',
      a2: 'NA',
      a3: 'NAM',
      num: '516',
      itu: 'NMB',
      gec: 'WA',
      ioc: 'NAM',
      fifa: 'NAM',
      ds: 'NAM',
      wmo: 'NM',
      gaul: '172',
      marc: 'sx',
      dial: '264',
      independent: 'Yes',
    ),
    Country(
      name: 'Nauru',
      a2: 'NR',
      a3: 'NRU',
      num: '520',
      itu: 'NRU',
      gec: 'NR',
      ioc: 'NRU',
      fifa: 'NRU',
      ds: 'NAU',
      wmo: 'NW',
      gaul: '173',
      marc: 'nu',
      dial: '674',
      independent: 'Yes',
    ),
    Country(
      name: 'Nepal',
      a2: 'NP',
      a3: 'NPL',
      num: '524',
      itu: 'NPL',
      gec: 'NP',
      ioc: 'NEP',
      fifa: 'NEP',
      ds: 'NEP',
      wmo: 'NP',
      gaul: '175',
      marc: 'np',
      dial: '977',
      independent: 'Yes',
    ),
    Country(
      name: 'Netherlands',
      a2: 'NL',
      a3: 'NLD',
      num: '528',
      itu: 'HOL',
      gec: 'NL',
      ioc: 'NED',
      fifa: 'NED',
      ds: 'NL',
      wmo: 'NL',
      gaul: '177',
      marc: 'ne',
      dial: '31',
      independent: 'Yes',
    ),
    Country(
      name: 'New Caledonia',
      a2: 'NC',
      a3: 'NCL',
      num: '540',
      itu: 'NCL',
      gec: 'NC',
      ioc: 'NCD',
      fifa: 'NCL',
      ds: 'F',
      wmo: 'NC',
      gaul: '178',
      marc: 'nl',
      dial: '687',
      independent: 'Territory of FR',
    ),
    Country(
      name: 'New Zealand',
      a2: 'NZ',
      a3: 'NZL',
      num: '554',
      itu: 'NZL',
      gec: 'NZ',
      ioc: 'NZL',
      fifa: 'NZL',
      ds: 'NZ',
      wmo: 'NZ',
      gaul: '179',
      marc: 'nz',
      dial: '64',
      independent: 'Yes',
    ),
    Country(
      name: 'Nicaragua',
      a2: 'NI',
      a3: 'NIC',
      num: '558',
      itu: 'NCG',
      gec: 'NU',
      ioc: 'NCA',
      fifa: 'NCA',
      ds: 'NIC',
      wmo: 'NK',
      gaul: '180',
      marc: 'nq',
      dial: '505',
      independent: 'Yes',
    ),
    Country(
      name: 'Niger',
      a2: 'NE',
      a3: 'NER',
      num: '562',
      itu: 'NGR',
      gec: 'NG',
      ioc: 'NIG',
      fifa: 'NIG',
      ds: 'RN',
      wmo: 'NR',
      gaul: '181',
      marc: 'ng',
      dial: '227',
      independent: 'Yes',
    ),
    Country(
      name: 'Nigeria',
      a2: 'NG',
      a3: 'NGA',
      num: '566',
      itu: 'NIG',
      gec: 'NI',
      ioc: 'NGR',
      fifa: 'NGA',
      ds: 'WAN',
      wmo: 'NI',
      gaul: '182',
      marc: 'nr',
      dial: '234',
      independent: 'Yes',
    ),
    Country(
      name: 'Niue',
      a2: 'NU',
      a3: 'NIU',
      num: '570',
      itu: 'NIU',
      gec: 'NE',
      ioc: 'NIU',
      fifa: 'NIU',
      ds: 'NZ',
      gaul: '183',
      marc: 'xh',
      dial: '683',
      independent: 'Associated with NZ',
    ),
    Country(
      name: 'Norfolk Island',
      a2: 'NF',
      a3: 'NFK',
      num: '574',
      itu: 'NFK',
      gec: 'NF',
      ioc: 'NFI',
      fifa: 'NFK',
      ds: 'AUS',
      wmo: 'NF',
      gaul: '184',
      marc: 'nx',
      dial: '672',
      independent: 'Territory of AU',
    ),
    Country(
      name: 'Northern Mariana Islands',
      a2: 'MP',
      a3: 'MNP',
      num: '580',
      itu: 'MRA',
      gec: 'CQ',
      ioc: 'NMA',
      fifa: 'NMI',
      ds: 'USA',
      wmo: 'MY',
      gaul: '185',
      marc: 'nw',
      dial: '1-670',
      independent: 'Commonwealth of US',
    ),
    Country(
      name: 'Norway',
      a2: 'NO',
      a3: 'NOR',
      num: '578',
      itu: 'NOR',
      gec: 'NO',
      ioc: 'NOR',
      fifa: 'NOR',
      ds: 'N',
      wmo: 'NO',
      gaul: '186',
      marc: 'no',
      dial: '47',
      independent: 'Yes',
    ),
    Country(
      name: 'Oman',
      a2: 'OM',
      a3: 'OMN',
      num: '512',
      itu: 'OMA',
      gec: 'MU',
      ioc: 'OMA',
      fifa: 'OMA',
      wmo: 'OM',
      gaul: '187',
      marc: 'mk',
      dial: '968',
      independent: 'Yes',
    ),
    Country(
      name: 'Pakistan',
      a2: 'PK',
      a3: 'PAK',
      num: '586',
      itu: 'PAK',
      gec: 'PK',
      ioc: 'PAK',
      fifa: 'PAK',
      ds: 'PK',
      wmo: 'PK',
      gaul: '188',
      marc: 'pk',
      dial: '92',
      independent: 'Yes',
    ),
    Country(
      name: 'Palau',
      a2: 'PW',
      a3: 'PLW',
      num: '585',
      itu: 'PLW',
      gec: 'PS',
      ioc: 'PLW',
      fifa: 'PLW',
      gaul: '189',
      marc: 'pw',
      dial: '680',
      independent: 'Yes',
    ),
    Country(
      name: 'Palestine',
      a2: 'PS',
      a3: 'PSE',
      num: '275',
      gec: 'GZ, WE',
      ioc: 'PLE',
      fifa: 'PLE',
      gaul: '91, 267',
      marc: 'gz, wj',
      dial: '970',
      independent: 'In contention',
    ),
    Country(
      name: 'Panama',
      a2: 'PA',
      a3: 'PAN',
      num: '591',
      itu: 'PNR',
      gec: 'PM',
      ioc: 'PAN',
      fifa: 'PAN',
      ds: 'PA',
      wmo: 'PM',
      gaul: '191',
      marc: 'pn',
      dial: '507',
      independent: 'Yes',
    ),
    Country(
      name: 'Papua New Guinea',
      a2: 'PG',
      a3: 'PNG',
      num: '598',
      itu: 'PNG',
      gec: 'PP',
      ioc: 'PNG',
      fifa: 'PNG',
      ds: 'PNG',
      wmo: 'NG',
      gaul: '192',
      marc: 'pp',
      dial: '675',
      independent: 'Yes',
    ),
    Country(
      name: 'Paraguay',
      a2: 'PY',
      a3: 'PRY',
      num: '600',
      itu: 'PRG',
      gec: 'PA',
      ioc: 'PAR',
      fifa: 'PAR',
      ds: 'PY',
      wmo: 'PY',
      gaul: '194',
      marc: 'py',
      dial: '595',
      independent: 'Yes',
    ),
    Country(
      name: 'Peru',
      a2: 'PE',
      a3: 'PER',
      num: '604',
      itu: 'PRU',
      gec: 'PE',
      ioc: 'PER',
      fifa: 'PER',
      ds: 'PE',
      wmo: 'PR',
      gaul: '195',
      marc: 'pe',
      dial: '51',
      independent: 'Yes',
    ),
    Country(
      name: 'Philippines',
      a2: 'PH',
      a3: 'PHL',
      num: '608',
      itu: 'PHL',
      gec: 'RP',
      ioc: 'PHI',
      fifa: 'PHI',
      ds: 'RP',
      wmo: 'PH',
      gaul: '196',
      marc: 'ph',
      dial: '63',
      independent: 'Yes',
    ),
    Country(
      name: 'Pitcairn',
      a2: 'PN',
      a3: 'PCN',
      num: '612',
      itu: 'PTC',
      gec: 'PC',
      fifa: 'PCN',
      wmo: 'PT',
      gaul: '197',
      marc: 'pc',
      dial: '870',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Poland',
      a2: 'PL',
      a3: 'POL',
      num: '616',
      itu: 'POL',
      gec: 'PL',
      ioc: 'POL',
      fifa: 'POL',
      ds: 'PL',
      wmo: 'PL',
      gaul: '198',
      marc: 'pl',
      dial: '48',
      independent: 'Yes',
    ),
    Country(
      name: 'Portugal',
      a2: 'PT',
      a3: 'PRT',
      num: '620',
      itu: 'POR',
      gec: 'PO',
      ioc: 'POR',
      fifa: 'POR',
      ds: 'P',
      wmo: 'PO',
      gaul: '199',
      marc: 'po',
      dial: '351',
      independent: 'Yes',
    ),
    Country(
      name: 'Puerto Rico',
      a2: 'PR',
      a3: 'PRI',
      num: '630',
      itu: 'PTR',
      gec: 'RQ',
      ioc: 'PUR',
      fifa: 'PUR',
      ds: 'USA',
      wmo: 'PU',
      gaul: '200',
      marc: 'pr',
      dial: '1',
      independent: 'Commonwealth of US',
    ),
    Country(
      name: 'Qatar',
      a2: 'QA',
      a3: 'QAT',
      num: '634',
      itu: 'QAT',
      gec: 'QA',
      ioc: 'QAT',
      fifa: 'QAT',
      ds: 'Q',
      wmo: 'QT',
      gaul: '201',
      marc: 'qa',
      dial: '974',
      independent: 'Yes',
    ),
    Country(
      name: 'Reunion',
      a2: 'RE',
      a3: 'REU',
      num: '638',
      itu: 'REU',
      gec: 'RE',
      ioc: 'REU',
      fifa: 'REU',
      ds: 'F',
      wmo: 'RE',
      gaul: '206',
      marc: 're',
      dial: '262',
      independent: 'Part of FR',
    ),
    Country(
      name: 'Romania',
      a2: 'RO',
      a3: 'ROU',
      num: '642',
      itu: 'ROU',
      gec: 'RO',
      ioc: 'ROU',
      fifa: 'ROU',
      ds: 'RO',
      wmo: 'RO',
      gaul: '203',
      marc: 'rm',
      dial: '40',
      independent: 'Yes',
    ),
    Country(
      name: 'Russian Federation',
      a2: 'RU',
      a3: 'RUS',
      num: '643',
      itu: 'RUS',
      gec: 'RS',
      ioc: 'RUS',
      fifa: 'RUS',
      ds: 'RUS',
      wmo: 'RS',
      gaul: '204',
      marc: 'ru',
      dial: '7',
      independent: 'Yes',
    ),
    Country(
      name: 'Rwanda',
      a2: 'RW',
      a3: 'RWA',
      num: '646',
      itu: 'RRW',
      gec: 'RW',
      ioc: 'RWA',
      fifa: 'RWA',
      ds: 'RWA',
      wmo: 'RW',
      gaul: '205',
      marc: 'rw',
      dial: '250',
      independent: 'Yes',
    ),
    Country(
      name: 'Saint Barthélemy',
      a2: 'BL',
      a3: 'BLM',
      num: '652',
      gec: 'TB',
      marc: 'sc',
      dial: '590',
      independent: 'Part of FR',
    ),
    Country(
      name: 'Saint Helena',
      a2: 'SH',
      a3: 'SHN',
      num: '654',
      itu: 'SHN',
      gec: 'SH',
      ioc: 'HEL',
      fifa: 'SHN',
      ds: 'SH',
      wmo: 'HE',
      gaul: '207',
      marc: 'xj',
      dial: '290, 247',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Saint Kitts and Nevis',
      a2: 'KN',
      a3: 'KNA',
      num: '659',
      itu: 'KNA',
      gec: 'SC',
      ioc: 'SKN',
      fifa: 'SKN',
      ds: 'KN',
      wmo: 'AT',
      gaul: '208',
      marc: 'xd',
      dial: '1-869',
      independent: 'Yes',
    ),
    Country(
      name: 'Saint Lucia',
      a2: 'LC',
      a3: 'LCA',
      num: '662',
      itu: 'LCA',
      gec: 'ST',
      ioc: 'LCA',
      fifa: 'LCA',
      ds: 'WL',
      wmo: 'LC',
      gaul: '209',
      marc: 'xk',
      dial: '1-758',
      independent: 'Yes',
    ),
    Country(
      name: 'Saint Martin (French part)',
      a2: 'MF',
      a3: 'MAF',
      num: '663',
      gec: 'RN',
      marc: 'st',
      dial: '590',
      independent: 'Part of FR',
    ),
    Country(
      name: 'Saint Pierre and Miquelon',
      a2: 'PM',
      a3: 'SPM',
      num: '666',
      itu: 'SPM',
      gec: 'SB',
      ioc: 'SPM',
      fifa: 'SPM',
      ds: 'F',
      wmo: 'FP',
      gaul: '210',
      marc: 'xl',
      dial: '508',
      independent: 'Part of FR',
    ),
    Country(
      name: 'Saint Vincent and the Grenadines',
      a2: 'VC',
      a3: 'VCT',
      num: '670',
      itu: 'VCT',
      gec: 'VC',
      ioc: 'VIN',
      fifa: 'VIN',
      ds: 'WV',
      wmo: 'VG',
      gaul: '211',
      marc: 'xm',
      dial: '1-784',
      independent: 'Yes',
    ),
    Country(
      name: 'Samoa',
      a2: 'WS',
      a3: 'WSM',
      num: '882',
      itu: 'SMO',
      gec: 'WS',
      ioc: 'SAM',
      fifa: 'SAM',
      ds: 'WS',
      wmo: 'ZM',
      gaul: '212',
      marc: 'ws',
      dial: '685',
      independent: 'Yes',
    ),
    Country(
      name: 'San Marino',
      a2: 'SM',
      a3: 'SMR',
      num: '674',
      itu: 'SMR',
      gec: 'SM',
      ioc: 'SMR',
      fifa: 'SMR',
      ds: 'RSM',
      gaul: '213',
      marc: 'sm',
      dial: '378',
      independent: 'Yes',
    ),
    Country(
      name: 'Sao Tome and Principe',
      a2: 'ST',
      a3: 'STP',
      num: '678',
      itu: 'STP',
      gec: 'TP',
      ioc: 'STP',
      fifa: 'STP',
      ds: 'ST',
      wmo: 'TP',
      gaul: '214',
      marc: 'sf',
      dial: '239',
      independent: 'Yes',
    ),
    Country(
      name: 'Saudi Arabia',
      a2: 'SA',
      a3: 'SAU',
      num: '682',
      itu: 'ARS',
      gec: 'SA',
      ioc: 'KSA',
      fifa: 'KSA',
      ds: 'SA',
      wmo: 'SD',
      gaul: '215',
      marc: 'su',
      dial: '966',
      independent: 'Yes',
    ),
    Country(
      name: 'Senegal',
      a2: 'SN',
      a3: 'SEN',
      num: '686',
      itu: 'SEN',
      gec: 'SG',
      ioc: 'SEN',
      fifa: 'SEN',
      ds: 'SN',
      wmo: 'SG',
      gaul: '217',
      marc: 'sg',
      dial: '221',
      independent: 'Yes',
    ),
    Country(
      name: 'Serbia',
      a2: 'RS',
      a3: 'SRB',
      num: '688',
      itu: 'SRB',
      gec: 'RI, KV',
      ioc: 'SRB',
      fifa: 'SRB',
      ds: 'SRB',
      wmo: 'YG',
      gaul: '2648',
      marc: 'rb',
      dial: '381',
      independent: 'Yes',
    ),
    Country(
      name: 'Seychelles',
      a2: 'SC',
      a3: 'SYC',
      num: '690',
      itu: 'SEY',
      gec: 'SE',
      ioc: 'SEY',
      fifa: 'SEY',
      ds: 'SY',
      wmo: 'SC',
      gaul: '220',
      marc: 'se',
      dial: '248',
      independent: 'Yes',
    ),
    Country(
      name: 'Sierra Leone',
      a2: 'SL',
      a3: 'SLE',
      num: '694',
      itu: 'SRL',
      gec: 'SL',
      ioc: 'SLE',
      fifa: 'SLE',
      ds: 'WAL',
      wmo: 'SL',
      gaul: '221',
      marc: 'sl',
      dial: '232',
      independent: 'Yes',
    ),
    Country(
      name: 'Singapore',
      a2: 'SG',
      a3: 'SGP',
      num: '702',
      itu: 'SNG',
      gec: 'SN',
      ioc: 'SIN',
      fifa: 'SIN',
      ds: 'SGP',
      wmo: 'SR',
      gaul: '222',
      marc: 'si',
      dial: '65',
      independent: 'Yes',
    ),
    Country(
      name: 'Sint Maarten',
      a2: 'SX',
      a3: 'SXM',
      num: '534',
      gec: 'NN',
      marc: 'sn',
      dial: '1-721',
      independent: 'Part of NL',
    ),
    Country(
      name: 'Slovakia',
      a2: 'SK',
      a3: 'SVK',
      num: '703',
      itu: 'SVK',
      gec: 'LO',
      ioc: 'SVK',
      fifa: 'SVK',
      ds: 'SK',
      wmo: 'SQ',
      gaul: '223',
      marc: 'xo',
      dial: '421',
      independent: 'Yes',
    ),
    Country(
      name: 'Slovenia',
      a2: 'SI',
      a3: 'SVN',
      num: '705',
      itu: 'SVN',
      gec: 'SI',
      ioc: 'SLO',
      fifa: 'SVN',
      ds: 'SLO',
      wmo: 'LJ',
      gaul: '224',
      marc: 'xv',
      dial: '386',
      independent: 'Yes',
    ),
    Country(
      name: 'Solomon Islands',
      a2: 'SB',
      a3: 'SLB',
      num: '90',
      itu: 'SLM',
      gec: 'BP',
      ioc: 'SOL',
      fifa: 'SOL',
      ds: 'SB',
      wmo: 'SO',
      gaul: '225',
      marc: 'bp',
      dial: '677',
      independent: 'Yes',
    ),
    Country(
      name: 'Somalia',
      a2: 'SO',
      a3: 'SOM',
      num: '706',
      itu: 'SOM',
      gec: 'SO',
      ioc: 'SOM',
      fifa: 'SOM',
      ds: 'SO',
      wmo: 'SI',
      gaul: '226',
      marc: 'so',
      dial: '252',
      independent: 'Yes',
    ),
    Country(
      name: 'South Africa',
      a2: 'ZA',
      a3: 'ZAF',
      num: '710',
      itu: 'AFS',
      gec: 'SF',
      ioc: 'RSA',
      fifa: 'RSA',
      ds: 'ZA',
      wmo: 'ZA',
      gaul: '227',
      marc: 'sa',
      dial: '27',
      independent: 'Yes',
    ),
    Country(
      name: 'South Georgia and South Sandwich Islands',
      a2: 'GS',
      a3: 'SGS',
      num: '239',
      gec: 'SX',
      gaul: '228',
      marc: 'xs',
      dial: '500',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'South Sudan',
      a2: 'SS',
      a3: 'SSD',
      num: '728',
      itu: 'SSD',
      gec: 'OD',
      marc: 'sd',
      dial: '211',
      independent: 'Yes',
    ),
    Country(
      name: 'Spain',
      a2: 'ES',
      a3: 'ESP',
      num: '724',
      itu: 'E',
      gec: 'SP',
      ioc: 'ESP',
      fifa: 'ESP',
      ds: 'E',
      wmo: 'SP',
      gaul: '229',
      marc: 'sp',
      dial: '34',
      independent: 'Yes',
    ),
    Country(
      name: 'Sri Lanka',
      a2: 'LK',
      a3: 'LKA',
      num: '144',
      itu: 'CLN',
      gec: 'CE',
      ioc: 'SRI',
      fifa: 'SRI',
      ds: 'CL',
      wmo: 'SB',
      gaul: '231',
      marc: 'ce',
      dial: '94',
      independent: 'Yes',
    ),
    Country(
      name: 'Sudan',
      a2: 'SD',
      a3: 'SDN',
      num: '729',
      itu: 'SDN',
      gec: 'SU',
      ioc: 'SUD',
      fifa: 'SUD',
      ds: 'SUD',
      wmo: 'SU',
      gaul: '40764',
      marc: 'sj',
      dial: '249',
      independent: 'Yes',
    ),
    Country(
      name: 'Suriname',
      a2: 'SR',
      a3: 'SUR',
      num: '740',
      itu: 'SUR',
      gec: 'NS',
      ioc: 'SUR',
      fifa: 'SUR',
      ds: 'SME',
      wmo: 'SM',
      gaul: '233',
      marc: 'sr',
      dial: '597',
      independent: 'Yes',
    ),
    Country(
      name: 'Svalbard and Jan Mayen Islands',
      a2: 'SJ',
      a3: 'SJM',
      num: '744',
      itu: 'NOR',
      gec: 'SV, JN',
      wmo: 'SZ',
      gaul: '234',
      dial: '47',
      independent: 'Territory of NO',
    ),
    Country(
      name: 'Swaziland',
      a2: 'SZ',
      a3: 'SWZ',
      num: '748',
      itu: 'SWZ',
      gec: 'WZ',
      ioc: 'SWZ',
      fifa: 'SWZ',
      ds: 'SD',
      wmo: 'SV',
      gaul: '235',
      marc: 'sq',
      dial: '268',
      independent: 'Yes',
    ),
    Country(
      name: 'Sweden',
      a2: 'SE',
      a3: 'SWE',
      num: '752',
      itu: 'S',
      gec: 'SW',
      ioc: 'SWE',
      fifa: 'SWE',
      ds: 'S',
      wmo: 'SN',
      gaul: '236',
      marc: 'sw',
      dial: '46',
      independent: 'Yes',
    ),
    Country(
      name: 'Switzerland',
      a2: 'CH',
      a3: 'CHE',
      num: '756',
      itu: 'SUI',
      gec: 'SZ',
      ioc: 'SUI',
      fifa: 'SUI',
      ds: 'CH',
      wmo: 'SW',
      gaul: '237',
      marc: 'sz',
      dial: '41',
      independent: 'Yes',
    ),
    Country(
      name: 'Syria',
      a2: 'SY',
      a3: 'SYR',
      num: '760',
      itu: 'SYR',
      gec: 'SY',
      ioc: 'SYR',
      fifa: 'SYR',
      ds: 'SYR',
      wmo: 'SY',
      gaul: '238',
      marc: 'sy',
      dial: '963',
      independent: 'Yes',
    ),
    Country(
      name: 'Taiwan',
      a2: 'TW',
      a3: 'TWN',
      num: '158',
      gec: 'TW',
      ioc: 'TPE',
      fifa: 'TPE',
      ds: 'RC',
      gaul: '925',
      marc: 'ch',
      dial: '886',
      independent: 'Yes',
    ),
    Country(
      name: 'Tajikistan',
      a2: 'TJ',
      a3: 'TJK',
      num: '762',
      itu: 'TJK',
      gec: 'TI',
      ioc: 'TJK',
      fifa: 'TJK',
      ds: 'TJ',
      wmo: 'TA',
      gaul: '239',
      marc: 'ta',
      dial: '992',
      independent: 'Yes',
    ),
    Country(
      name: 'Tanzania',
      a2: 'TZ',
      a3: 'TZA',
      num: '834',
      itu: 'TZA',
      gec: 'TZ',
      ioc: 'TAN',
      fifa: 'TAN',
      ds: 'EAT',
      wmo: 'TN',
      gaul: '257',
      marc: 'tz',
      dial: '255',
      independent: 'Yes',
    ),
    Country(
      name: 'Thailand',
      a2: 'TH',
      a3: 'THA',
      num: '764',
      itu: 'THA',
      gec: 'TH',
      ioc: 'THA',
      fifa: 'THA',
      ds: 'T',
      wmo: 'TH',
      gaul: '240',
      marc: 'th',
      dial: '66',
      independent: 'Yes',
    ),
    Country(
      name: 'Timor-Leste',
      a2: 'TL',
      a3: 'TLS',
      num: '626',
      itu: 'TLS',
      gec: 'TT',
      ioc: 'TLS',
      fifa: 'TLS',
      ds: 'RI',
      wmo: 'TM',
      gaul: '242',
      marc: 'em',
      dial: '670',
      independent: 'Yes',
    ),
    Country(
      name: 'Togo',
      a2: 'TG',
      a3: 'TGO',
      num: '768',
      itu: 'TGO',
      gec: 'TO',
      ioc: 'TOG',
      fifa: 'TOG',
      ds: 'TG',
      wmo: 'TG',
      gaul: '243',
      marc: 'tg',
      dial: '228',
      independent: 'Yes',
    ),
    Country(
      name: 'Tokelau',
      a2: 'TK',
      a3: 'TKL',
      num: '772',
      itu: 'TKL',
      gec: 'TL',
      fifa: 'TKL',
      ds: 'NZ',
      wmo: 'TK',
      gaul: '244',
      marc: 'tl',
      dial: '690',
      independent: 'Territory of NZ',
    ),
    Country(
      name: 'Tonga',
      a2: 'TO',
      a3: 'TON',
      num: '776',
      itu: 'TON',
      gec: 'TN',
      ioc: 'TGA',
      fifa: 'TGA',
      ds: 'TO',
      wmo: 'TO',
      gaul: '245',
      marc: 'to',
      dial: '676',
      independent: 'Yes',
    ),
    Country(
      name: 'Trinidad and Tobago',
      a2: 'TT',
      a3: 'TTO',
      num: '780',
      itu: 'TRD',
      gec: 'TD',
      ioc: 'TTO',
      fifa: 'TRI',
      ds: 'TT',
      wmo: 'TD',
      gaul: '246',
      marc: 'tr',
      dial: '1-868',
      independent: 'Yes',
    ),
    Country(
      name: 'Tunisia',
      a2: 'TN',
      a3: 'TUN',
      num: '788',
      itu: 'TUN',
      gec: 'TS',
      ioc: 'TUN',
      fifa: 'TUN',
      ds: 'TN',
      wmo: 'TS',
      gaul: '248',
      marc: 'ti',
      dial: '216',
      independent: 'Yes',
    ),
    Country(
      name: 'Turkey',
      a2: 'TR',
      a3: 'TUR',
      num: '792',
      itu: 'TUR',
      gec: 'TU',
      ioc: 'TUR',
      fifa: 'TUR',
      ds: 'TR',
      wmo: 'TU',
      gaul: '249',
      marc: 'tu',
      dial: '90',
      independent: 'Yes',
    ),
    Country(
      name: 'Turkmenistan',
      a2: 'TM',
      a3: 'TKM',
      num: '795',
      itu: 'TKM',
      gec: 'TX',
      ioc: 'TKM',
      fifa: 'TKM',
      ds: 'TM',
      wmo: 'TR',
      gaul: '250',
      marc: 'tk',
      dial: '993',
      independent: 'Yes',
    ),
    Country(
      name: 'Turks and Caicos Islands',
      a2: 'TC',
      a3: 'TCA',
      num: '796',
      itu: 'TCA',
      gec: 'TK',
      ioc: 'TKS',
      fifa: 'TCA',
      wmo: 'TI',
      gaul: '251',
      marc: 'tc',
      dial: '1-649',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Tuvalu',
      a2: 'TV',
      a3: 'TUV',
      num: '798',
      itu: 'TUV',
      gec: 'TV',
      ioc: 'TUV',
      fifa: 'TUV',
      ds: 'TV',
      wmo: 'TV',
      gaul: '252',
      marc: 'tv',
      dial: '688',
      independent: 'Yes',
    ),
    Country(
      name: 'Uganda',
      a2: 'UG',
      a3: 'UGA',
      num: '800',
      itu: 'UGA',
      gec: 'UG',
      ioc: 'UGA',
      fifa: 'UGA',
      ds: 'EAU',
      wmo: 'UG',
      gaul: '253',
      marc: 'ug',
      dial: '256',
      independent: 'Yes',
    ),
    Country(
      name: 'Ukraine',
      a2: 'UA',
      a3: 'UKR',
      num: '804',
      itu: 'UKR',
      gec: 'UP',
      ioc: 'UKR',
      fifa: 'UKR',
      ds: 'UA',
      wmo: 'UR',
      gaul: '254',
      marc: 'un',
      dial: '380',
      independent: 'Yes',
    ),
    Country(
      name: 'United Arab Emirates',
      a2: 'AE',
      a3: 'ARE',
      num: '784',
      itu: 'UAE',
      gec: 'AE',
      ioc: 'UAE',
      fifa: 'UAE',
      wmo: 'ER',
      gaul: '255',
      marc: 'ts',
      dial: '971',
      independent: 'Yes',
    ),
    Country(
      name: 'United Kingdom',
      a2: 'GB',
      a3: 'GBR',
      num: '826',
      itu: 'G',
      gec: 'UK',
      ioc: 'GBR',
      fifa: 'ENG, NIR, SCO, WAL',
      ds: 'GB',
      wmo: 'UK',
      gaul: '256',
      marc: 'xxk',
      dial: '44',
      independent: 'Yes',
    ),
    Country(
      name: 'United States Minor Outlying Islands',
      a2: 'UM',
      a3: 'UMI',
      num: '581',
      ds: 'USA',
      independent: 'Territories of US',
    ),
    Country(
      name: 'United States of America',
      a2: 'US',
      a3: 'USA',
      num: '840',
      itu: 'USA',
      gec: 'US',
      ioc: 'USA',
      fifa: 'USA',
      ds: 'USA',
      wmo: 'US',
      gaul: '259',
      marc: 'xxu',
      dial: '1',
      independent: 'Yes',
    ),
    Country(
      name: 'Uruguay',
      a2: 'UY',
      a3: 'URY',
      num: '858',
      itu: 'URG',
      gec: 'UY',
      ioc: 'URU',
      fifa: 'URU',
      ds: 'ROU',
      wmo: 'UY',
      gaul: '260',
      marc: 'uy',
      dial: '598',
      independent: 'Yes',
    ),
    Country(
      name: 'Uzbekistan',
      a2: 'UZ',
      a3: 'UZB',
      num: '860',
      itu: 'UZB',
      gec: 'UZ',
      ioc: 'UZB',
      fifa: 'UZB',
      ds: 'UZ',
      wmo: 'UZ',
      gaul: '261',
      marc: 'uz',
      dial: '998',
      independent: 'Yes',
    ),
    Country(
      name: 'Vanuatu',
      a2: 'VU',
      a3: 'VUT',
      num: '548',
      itu: 'VUT',
      gec: 'NH',
      ioc: 'VAN',
      fifa: 'VAN',
      ds: 'VU',
      wmo: 'NV',
      gaul: '262',
      marc: 'nn',
      dial: '678',
      independent: 'Yes',
    ),
    Country(
      name: 'Vatican City',
      a2: 'VA',
      a3: 'VAT',
      num: '336',
      itu: 'CVA',
      gec: 'VT',
      fifa: 'VAT',
      ds: 'V',
      wmo: '',
      gaul: '110',
      marc: 'vc',
      dial: '39-06',
      independent: 'Yes',
    ),
    Country(
      name: 'Venezuela',
      a2: 'VE',
      a3: 'VEN',
      num: '862',
      itu: 'VEN',
      gec: 'VE',
      ioc: 'VEN',
      fifa: 'VEN',
      ds: 'YV',
      wmo: 'VN',
      gaul: '263',
      marc: 've',
      dial: '58',
      independent: 'Yes',
    ),
    Country(
      name: 'Vietnam',
      a2: 'VN',
      a3: 'VNM',
      num: '704',
      itu: 'VTN',
      gec: 'VM',
      ioc: 'VIE',
      fifa: 'VIE',
      ds: 'VN',
      wmo: 'VS',
      gaul: '264',
      marc: 'vm',
      dial: '84',
      independent: 'Yes',
    ),
    Country(
      name: 'Virgin Islands, British',
      a2: 'VG',
      a3: 'VGB',
      num: '92',
      itu: 'VRG',
      gec: 'VI',
      ioc: 'IVB',
      fifa: 'VGB',
      ds: 'BVI',
      wmo: 'VI',
      gaul: '39',
      marc: 'vb',
      dial: '1-284',
      independent: 'Territory of GB',
    ),
    Country(
      name: 'Virgin Islands, U.S.',
      a2: 'VI',
      a3: 'VIR',
      num: '850',
      itu: 'VIR',
      gec: 'VQ',
      ioc: 'ISV',
      fifa: 'VIR',
      ds: 'USA',
      wmo: 'VI',
      gaul: '258',
      marc: 'vi',
      dial: '1-340',
      independent: 'Territory of US',
    ),
    Country(
      name: 'Wallis and Futuna Islands',
      a2: 'WF',
      a3: 'WLF',
      num: '876',
      itu: 'WAL',
      gec: 'WF',
      ioc: 'WAF',
      fifa: 'WLF',
      ds: 'F',
      wmo: 'FW',
      gaul: '266',
      marc: 'wf',
      dial: '681',
      independent: 'Territory of FR',
    ),
    Country(
      name: 'Western Sahara',
      a2: 'EH',
      a3: 'ESH',
      num: '732',
      itu: 'AOE',
      gec: 'WI',
      fifa: 'SAH',
      gaul: '268',
      marc: 'ss',
      dial: '212',
      independent: 'In contention',
    ),
    Country(
      name: 'Yemen',
      a2: 'YE',
      a3: 'YEM',
      num: '887',
      itu: 'YEM',
      gec: 'YM',
      ioc: 'YEM',
      fifa: 'YEM',
      ds: 'YAR',
      wmo: 'YE',
      gaul: '269',
      marc: 'ye',
      dial: '967',
      independent: 'Yes',
    ),
    Country(
      name: 'Zambia',
      a2: 'ZM',
      a3: 'ZMB',
      num: '894',
      itu: 'ZMB',
      gec: 'ZA',
      ioc: 'ZAM',
      fifa: 'ZAM',
      ds: 'Z',
      wmo: 'ZB',
      gaul: '270',
      marc: 'za',
      dial: '260',
      independent: 'Yes',
    ),
    Country(
      name: 'Zimbabwe',
      a2: 'ZW',
      a3: 'ZWE',
      num: '716',
      itu: 'ZWE',
      gec: 'ZI',
      ioc: 'ZIM',
      fifa: 'ZIM',
      ds: 'ZW',
      wmo: 'ZW',
      gaul: '271',
      marc: 'rh',
      dial: '263',
      independent: 'Yes',
    )
  ];
}

class Country {
  final String name;
  final String? localizedName;
  final String? a2;
  final String? a3;
  final String? num;
  final String? itu;
  final String? gec;
  final String? ioc;
  final String? fifa;
  final String? ds;
  final String? wmo;
  final String? gaul;
  final String? marc;
  final String? dial;
  final String? independent;

  Country({
    required this.name,
    this.localizedName,
    this.a2,
    this.a3,
    this.num,
    this.itu,
    this.gec,
    this.ioc,
    this.fifa,
    this.ds,
    this.wmo,
    this.gaul,
    this.marc,
    this.dial,
    this.independent,
  });

  Country.withLocalization(Country country, this.localizedName)
      : name = country.name,
        a2 = country.a2,
        a3 = country.a3,
        num = country.num,
        itu = country.itu,
        gec = country.gec,
        ioc = country.ioc,
        fifa = country.fifa,
        ds = country.ds,
        wmo = country.wmo,
        gaul = country.gaul,
        marc = country.marc,
        dial = country.dial,
        independent = country.independent;
}
